Разметка всех страниц
htmlacademy-adaptive/2205907-cat-energy-27 pull request #2
Opened 2022-11-27 13:15 UTC by yunussovd

2022-11-28 14:12 UTC, Dima-Dim requested changes
Довольно много ошибок по БЭМ.

2022-11-28 14:12 UTC, Dima-Dim commented on source/index.html
> +      <li class="footer-socials__item">
Почему логотип является частью списка социальных сетей?

2022-11-29 11:01 UTC, yunussovd commented on source/index.html
> +      <li class="footer-socials__item">
Могу изменить класс на футер лист, чтобы более обще звучало, тогда что угодно можно будет вставить

2022-11-29 11:25 UTC, Dima-Dim commented on source/index.html
> +      <li class="footer-socials__item">
Дело не в названии класса, а в том, в какой логической структуре находится этот элемент.

2022-11-29 13:12 UTC, yunussovd commented on source/index.html
> +      <li class="footer-socials__item">
Лог структура в данном случае все ссылки, которые есть в футере

2022-11-29 13:12 UTC, yunussovd commented on source/catalog.html
> +          <div class="product__description">
убрал div и лишний ul

2022-11-29 13:19 UTC, yunussovd commented on source/index.html
> +      <li class="footer-socials__item">
Там ведь список, лого своеобразная ссылка, но ,думаю, думаю она просто будет отправлять к началу страницы

2022-11-29 13:34 UTC, Dima-Dim commented on source/index.html
> +      <li class="footer-socials__item">
Но мы же не объединяем по такому принципы в списки все блоки в любом месте :) В список объединят одинаковые по смыслу сущности, а не всё подряд где-то.

2022-11-29 14:07 UTC, yunussovd commented on source/index.html
> +      <li class="footer-socials__item">
Убрал ul вовсе, сейчас все в потоке, без обертки, можно будет толкаться отступами как на десктопе, так и в мобилке, а на мобилке блока ширину можно будет задать, чтобы они одна ссылку целую строку занимала

2022-11-30 07:35 UTC, Dima-Dim requested changes

2022-11-30 07:35 UTC, Dima-Dim commented on source/catalog.html
> +          <p class="products-weight">Масса</p>
Каждая такая строка это самодостаточный блок? В теории такое возможно, но на практике в чём смысл? Ведь он не существует вне `products__card`.
Ну и по критерия на каждый блок нужно будет создать отдельный файл со стилями. Если на каждую строку делать блок, то это приведёт к обратному эффекту от ожидаемого удобства.

2022-11-30 07:35 UTC, Dima-Dim commented on source/catalog.html
> +        <li class="products__card products__card-extra">
`card-extra` скорее модификатор.

2022-11-30 07:35 UTC, Dima-Dim commented on source/form.html
> +        <h3 class="visually-hidden">Данные кота</h3>
Не нужно перебарщивать со скрытыми текстами.

2022-11-30 07:35 UTC, Dima-Dim commented on source/form.html
>              <label for="pet-name">Имя:*</label>
Тоже блок сам по себе без особой необходимости.

2022-11-30 07:35 UTC, Dima-Dim commented on source/form.html
> +            <input class="select-radio" type="radio" id="weight-gain" name="program-selection">
Тоже какие-то странные блоки. Блок для `radio` это нормально, но блок для каждого элемента - перебор.

2022-11-30 07:35 UTC, Dima-Dim commented on source/index.html
> +    <a class="page-footer__link" href="https://vk.com/htmlacademy">
А вот тут список ломать ну нужно было. Странно что вопросы которые прорабатываются на 1-ом уровне всплывают на 2-ом.

2022-11-30 12:28 UTC, yunussovd commented on source/catalog.html
> +          <p class="products-weight">Масса</p>
Вы имеете ввиду products-weight и тд? там хотел продактс имя блока, а вес имя элемента, опечатался

2022-11-30 12:30 UTC, Dima-Dim commented on source/catalog.html
> +          <p class="products-weight">Масса</p>
Тогда нужно поправить опечатки.

2022-11-30 12:34 UTC, yunussovd commented on source/form.html
> +        <h3 class="visually-hidden">Данные кота</h3>
Делал для дерева, + скринридер будет понимать, что за блок, поэтому сделал к каждому полю заголовок, к которому относятся поля

2022-11-30 12:35 UTC, yunussovd commented on source/form.html
>              <label for="pet-name">Имя:*</label>
в плане?

2022-11-30 12:35 UTC, yunussovd commented on source/form.html
>              <label for="pet-name">Имя:*</label>
Понял, типо можно убрать list и оставить элементы просто

2022-11-30 13:06 UTC, yunussovd commented on source/index.html
> +      <li class="footer-socials__item">
> Но мы же не объединяем по такому принципы в списки все блоки в любом месте :) В список объединят одинаковые по смыслу сущности, а не всё подряд где-то.

Начинаю понимать)

2022-11-30 13:26 UTC, yunussovd commented on source/catalog.html
> +          <p class="products-weight">Масса</p>
Классы переосмыслил, исправляю все

2022-11-30 13:31 UTC, Dima-Dim commented on source/form.html
>              <label for="pet-name">Имя:*</label>
Не, тут ошибся `pet-name` по считал за `class`. Список можно оставить, он может пригодиться.

2022-11-30 14:04 UTC, yunussovd commented
Переиспользование чутка переосмыслил, оказалось в каталоге уже неплохо было, сейчас должно быть лучше и разметка чуть легче стала

2022-11-30 14:24 UTC, Dima-Dim requested changes
Проверься валидатором и поправь ошибки, на которые он указывает.

2022-12-01 08:18 UTC, merged