#4 Adaptive grid
htmlacademy-adaptive/2205907-cat-energy-27 pull request #5
Opened 2022-12-25 13:50 UTC by yunussovd

Adding new styles according to meadia requests for tablet and desktop view

2022-12-25 14:07 UTC, yunussovd commented
Есть небольшие задачи , которые нужно решить, но пока не знаю как) резину пока не делал, попробовал, не пошло, пока только под размеры разные верстку сделал

2022-12-27 14:40 UTC, Dima-Dim requested changes

2022-12-27 14:40 UTC, Dima-Dim commented on source/less/blocks/advantages.less
> +@media (min-width: @tablet-width) {
Не нужно так делать. При таком расположении медиавыражений не удобно следить за тем, как изменятся стили блока. Нужно постоянно ходить туда сюда по файлу и искать нужный селектор. Лучше располагать медиавыражения внутри селекторов.

2022-12-27 14:40 UTC, Dima-Dim commented on source/less/blocks/button.less
> +  .catalog {
Это же файл для блока `button`.

2022-12-27 14:40 UTC, Dima-Dim commented on source/less/blocks/form.less
> +}
Размер файла намекает на то, что тут не один блок.

2022-12-27 14:40 UTC, Dima-Dim commented on source/less/blocks/header.less
> +  .main-nav__link--current {
В это файле только блок `header` должен быть. Так же как и в других файлах блоков могут быть описаны только эти блоки.

2022-12-28 11:31 UTC, yunussovd commented on source/less/blocks/header.less
> +  .main-nav__link--current {
Исправил

2022-12-28 11:34 UTC, yunussovd commented on source/less/blocks/form.less
> +}
Там один блок, но внутри много элементов

2022-12-28 11:36 UTC, yunussovd commented on source/less/blocks/button.less
> +  .catalog {
Исправил, нужны быть повнимательнее мне

2023-01-02 15:30 UTC, merged