№5 Decorative elements
htmlacademy-adaptive/2205907-cat-energy-27 pull request #6
Opened 2023-01-10 15:26 UTC by yunussovd

Decorative elements, main-nav+js was added

2023-01-10 15:50 UTC, yunussovd commented
Задачу с фоном на десктопе пока не решил, пока только мысли с изменением разметки, но это костыльно
Меню на мобилке сделал по-своему, изначально хотел зайти не со смены классов, а со смены стилей, в итоге смешал, интересно ваше мнение
Картинки пока вставлял, брал разные размеру, в след блоках будет на все одна картинка для оптимиации верстки, сейчас достаточно тяжелая

2023-01-10 15:53 UTC, yunussovd commented
Протестировал на телефона меню на мобилке, что-то не работает, на компе в симуляторе клик, на мобилке касание, но что-то не реагирует

2023-01-10 16:02 UTC, yunussovd commented
И не понимаю, как избавиться от этого отступа, на телефоне он тоже присутсвует 
![image](https://user-images.githubusercontent.com/72697879/211601011-627e391e-9c4a-4bd1-b51b-7aab3a3f66da.png)

2023-01-11 05:24 UTC, Dima-Dim commented
> И не понимаю, как избавиться от этого отступа, на телефоне он тоже присутсвует ![image](https://user-images.githubusercontent.com/72697879/211601011-627e391e-9c4a-4bd1-b51b-7aab3a3f66da.png)

У тебя появляется горизонтальный скрол, на этой ширине и больше его быть не должно. Ищи элемент который "торчит" за вьюпорт.

2023-01-11 05:25 UTC, Dima-Dim commented
> Протестировал на телефона меню на мобилке, что-то не работает, на компе в симуляторе клик, на мобилке касание, но что-то не реагирует в safari и chrome, в статье stackoverflow пишут, что иногда сафари или мобилка не оч видят click ивент

Есть проблема с подключением JS-а. https://htmlacademy-adaptive.github.io/2205907-cat-energy-27/6/ и посмотреть в консоль.

2023-01-11 06:21 UTC, Dima-Dim requested changes
[advantages__consistency--desk.png](https://github.com/htmlacademy-adaptive/2205907-cat-energy-27/pull/6/files#diff-f092fcc7ba1c759d26a0e579e06bfcb43536629716c8a6f69bd7a605bc7c7c88) и другие изображения точно не svg?

2023-01-11 06:21 UTC, Dima-Dim commented on source/script.js
> +    navToggle.style.backgroundImage = "url('../img/close-menu--mob.svg')";
Это лучше делать в css использую классы которые появляются или исчезают.

2023-01-12 13:34 UTC, yunussovd commented on source/less/blocks/advantages.less
>  @media (min-width: @tablet-width) {
Исправил, теперь сортировка не по медиа выражениям, а по классам, а медиа выражения в классах

2023-01-14 09:07 UTC, yunussovd commented on source/less/blocks/advantages.less
> +  width: 60px;
Исправил

2023-01-14 10:12 UTC, yunussovd commented on source/script.js
> +    navToggle.style.backgroundImage = "url('../img/close-menu--mob.svg')";
Cделал, не без помощи ютуба, но сделал)

2023-01-14 10:14 UTC, yunussovd commented
> И не понимаю, как избавиться от этого отступа, на телефоне он тоже присутсвует ![image](https://user-images.githubusercontent.com/72697879/211601011-627e391e-9c4a-4bd1-b51b-7aab3a3f66da.png)

искал, но у меня 0 таких элементов, все в рамках тела <html>

2023-01-14 14:39 UTC, Dima-Dim commented
> искал, но у меня 0 таких элементов, все в рамках тела 

Сейчас вроде всё хорошо, полосы нет, видимо действительно стало 0.

2023-01-14 14:39 UTC, merged

2023-01-14 21:23 UTC, yunussovd commented
> > искал, но у меня 0 таких элементов, все в рамках тела
> 
> Сейчас вроде всё хорошо, полосы нет, видимо действительно стало 0.

Горизонтальный скролл есть, на десктопе в мобилке и на телефоне тоже, но какой элемент не пускает  не знаю